[project]
name = "yuno-kickstart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rodrigo Costa", email = "rmcosta@outlook.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
yuno-kickstart = "yuno_kickstart:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyyaml>=6.0.3",
]
