"""Provider-neutral realtime voice contracts."""

from yuno_backend.volta.realtime.client_secrets import (
    RealtimeClientSecret,
    RealtimeClientSecretIssuer,
    RealtimeClientSecretRequest,
)
from yuno_backend.volta.realtime.errors import (
    InvalidRealtimeEvent,
    InvalidRealtimeResponseError,
    RealtimeAuthenticationError,
    RealtimeConnectionError,
    RealtimeDisconnectedError,
    RealtimeError,
    RealtimeModelUnavailableError,
    RealtimeProviderError,
    RealtimeRateLimitError,
    RealtimeTimeoutError,
)
from yuno_backend.volta.realtime.gateway import RealtimeConnection, RealtimeGateway
from yuno_backend.volta.realtime.models import (
    PcmAudioFormat,
    RealtimeAudioDelta,
    RealtimeEvent,
    RealtimePlaybackTruncation,
    RealtimeResponseCancelled,
    RealtimeResponseCompleted,
    RealtimeSessionReady,
    RealtimeSessionRequest,
    RealtimeSpeechStarted,
    RealtimeSpeechStopped,
    RealtimeToolCallRequested,
    RealtimeToolDefinition,
    RealtimeToolOutput,
)

__all__ = [
    "InvalidRealtimeEvent",
    "InvalidRealtimeResponseError",
    "PcmAudioFormat",
    "RealtimeAudioDelta",
    "RealtimeAuthenticationError",
    "RealtimeClientSecret",
    "RealtimeClientSecretIssuer",
    "RealtimeClientSecretRequest",
    "RealtimeConnection",
    "RealtimeConnectionError",
    "RealtimeDisconnectedError",
    "RealtimeError",
    "RealtimeEvent",
    "RealtimeGateway",
    "RealtimeModelUnavailableError",
    "RealtimePlaybackTruncation",
    "RealtimeProviderError",
    "RealtimeRateLimitError",
    "RealtimeResponseCancelled",
    "RealtimeResponseCompleted",
    "RealtimeSessionReady",
    "RealtimeSessionRequest",
    "RealtimeSpeechStarted",
    "RealtimeSpeechStopped",
    "RealtimeTimeoutError",
    "RealtimeToolCallRequested",
    "RealtimeToolDefinition",
    "RealtimeToolOutput",
]
